// reVC-PS3: English text for the menu keys reVC adds to the PC game. The PC
// american.gxt the user copies doesn't have them ("FEG_FPS missing" in the
// menu); CText::Get falls back to these (reVC's gamefiles, plus the port's own).
static const struct { const char *key; const char *text; } ps3TextFallback[] = {
	{ "FEG_FPS", "SHOW FPS" },	// reVC-PS3's own
	{ "FED_PSF", "SCREEN SIZE" },	// reVC-PS3's own
	{ "FEG_FRT", "FRAME RATE" },	// reVC-PS3's own
	{ "FEG_F30", "30 FPS" },	// reVC-PS3's own
	{ "FEG_F60", "60 FPS" },	// reVC-PS3's own
	{ "FEH_MPS", "STICK/D-PAD MOVE - ~J~ ~V~ ZOOM - ~X~ WAYPOINT - ~K~ LEGEND" },	// reVC-PS3's own
	{ "CRIMRA", "Criminal rating:" },
	{ "FEA_2SP", "2 Speakers" },
	{ "FEA_3DH", "AUDIO HARDWARE" },
	{ "FEA_4SP", "More than 2 speakers" },
	{ "FEA_ADP", "AUTO-DETECT HARDWARE" },
	{ "FEA_EAR", "Headphones" },
	{ "FEA_FM0", "WILDSTYLE" },
	{ "FEA_FM1", "FLASH FM" },
	{ "FEA_FM2", "KCHAT" },
	{ "FEA_FM3", "FEVER 105" },
	{ "FEA_FM4", "VROCK" },
	{ "FEA_FM5", "VCPR" },
	{ "FEA_FM6", "ESPANTOSO" },
	{ "FEA_FM7", "EMOTION 98.3" },
	{ "FEA_FM8", "WAVE 103" },
	{ "FEA_MP3", "MP3 PLAYER" },
	{ "FEA_MPB", "MP3 VOLUME BOOST" },
	{ "FEA_MUS", "MUSIC VOLUME" },
	{ "FEA_NAH", "NO AUDIO HARDWARE" },
	{ "FEA_NM3", "NO MP3 FILES FOUND" },
	{ "FEA_RSS", "Radio station" },
	{ "FEA_SFX", "SFX VOLUME" },
	{ "FEA_SPK", "SPEAKERS CONFIGURATION" },
	{ "FEC_360", "XBOX 360 CONTROLLER" },
	{ "FEC_ACC", "Accelerate" },
	{ "FEC_ANS", "Action" },
	{ "FEC_ATT", "Attack or Fire weapon" },
	{ "FEC_BAC", "Backwards" },
	{ "FEC_BRA", "Brake or Reverse" },
	{ "FEC_BSP", "BSPACE" },
	{ "FEC_CAM", "Camera modes" },
	{ "FEC_CAW", "Car weapon" },
	{ "FEC_CCF", "Configuration" },
	{ "FEC_CCM", "Center Camera Behind player." },
	{ "FEC_CDP", "Controller Display" },
	{ "FEC_CEN", "Center camera" },
	{ "FEC_CF1", "Setup 1" },
	{ "FEC_CF2", "Setup 2" },
	{ "FEC_CF3", "Setup 3" },
	{ "FEC_CF4", "Setup 4" },
	{ "FEC_CLK", "CAPSLOCK" },
	{ "FEC_CMP", "COMBO: LOOK L+R" },
	{ "FEC_CMR", "Change camera" },
	{ "FEC_CR3", "Crouch (L3 button)" },
	{ "FEC_CRO", "Crouch" },
	{ "FEC_CWL", "Cycle Weapon left" },
	{ "FEC_CWR", "Cycle Weapon right" },
	{ "FEC_DBG", "DEBUG MENU" },
	{ "FEC_DLL", "DEL" },
	{ "FEC_DOT", "NUM ." },
	{ "FEC_DS2", "DUALSHOCK 2" },
	{ "FEC_DS3", "DUALSHOCK 3" },
	{ "FEC_DS4", "DUALSHOCK 4" },
	{ "FEC_DWA", "DOWN" },
	{ "FEC_EEX", "Enter+exit" },
	{ "FEC_END", "END" },
	{ "FEC_ENV", "Enter vehicle" },
	{ "FEC_ETR", "ENT" },
	{ "FEC_EXV", "Enter and exit vehicle" },
	{ "FEC_FIR", "Fire" },
	{ "FEC_FNC", "F~1~" },
	{ "FEC_FOR", "Forward" },
	{ "FEC_FPC", "First person camera" },
	{ "FEC_FRC", "FREE CAM" },
	{ "FEC_FWS", "NUM /" },
	{ "FEC_HAB", "Hand brake" },
	{ "FEC_HME", "HOME" },
	{ "FEC_HND", "Handbrake" },
	{ "FEC_HO3", "Horn (L3 button)" },
	{ "FEC_HOR", "Horn" },
	{ "FEC_HRN", "Horn" },
	{ "FEC_IBT", "-" },
	{ "FEC_ILU", "Invert Look in 1st Person" },
	{ "FEC_INC", "In car" },
	{ "FEC_IRT", "INS" },
	{ "FEC_IVV", "INVERT MOUSE VERTICALLY" },
	{ "FEC_JBO", "JOY ~1~" },
	{ "FEC_JDE", "Detected joystick" },
	{ "FEC_JMP", "Jump" },
	{ "FEC_JOD", "DETECT JOYSTICK" },
	{ "FEC_JUM", "Jump" },
	{ "FEC_LAL", "LALT" },
	{ "FEC_LB", "Look behind" },
	{ "FEC_LB3", "Look behind" },
	{ "FEC_LBA", "Look behind" },
	{ "FEC_LBC", "Use Look Left With Look Right." },
	{ "FEC_LCT", "LCTRL" },
	{ "FEC_LDN", "1st Person Look Down" },
	{ "FEC_LDU", "Look Down" },
	{ "FEC_LEF", "Left" },
	{ "FEC_LFA", "LEFT" },
	{ "FEC_LKT", "Lock Target" },
	{ "FEC_LL", "Look left" },
	{ "FEC_LOF", "Look forward" },
	{ "FEC_LOL", "Look left" },
	{ "FEC_LOR", "Look right" },
	{ "FEC_LR", "Look right" },
	{ "FEC_LSF", "LSHIFT" },
	{ "FEC_LUD", "Look Up" },
	{ "FEC_LUP", "1st Person Look Up" },
	{ "FEC_LWD", "LWIN" },
	{ "FEC_MIN", "NUM -" },
	{ "FEC_MOU", "Mouse Settings" },
	{ "FEC_MOV", "Movement" },
	{ "FEC_MSH", "MOUSE SENSITIVITY" },
	{ "FEC_MSL", "LMB" },
	{ "FEC_MSM", "MMB" },
	{ "FEC_MSR", "RMB" },
	{ "FEC_MWB", "MS WHEEL DN" },
	{ "FEC_MWF", "MS WHEEL UP" },
	{ "FEC_MXO", "MXB1" },
	{ "FEC_MXT", "MXB2" },
	{ "FEC_NA", "NA" },
	{ "FEC_NLK", "NUMLOCK" },
	{ "FEC_NMN", "NUM~1~" },
	{ "FEC_NTR", "Next target" },
	{ "FEC_NUS", "NOT USED" },
	{ "FEC_NWE", "Next weapon" },
	{ "FEC_OKK", "O.K." },
	{ "FEC_ONE", "XBOX ONE CONTROLLER" },
	{ "FEC_ONF", "On foot" },
	{ "FEC_ORR", "or" },
	{ "FEC_PAU", "Pause" },
	{ "FEC_PGD", "PGDN" },
	{ "FEC_PGU", "PGUP" },
	{ "FEC_PJP", "Ped Jump" },
	{ "FEC_PLB", "Look Behind." },
	{ "FEC_PLS", "NUM +" },
	{ "FEC_PSB", "BREAK" },
	{ "FEC_PSP", "Ped Sprint" },
	{ "FEC_PTL", "Use LockTarget with Weapon Switch Left." },
	{ "FEC_PTR", "Use LockTarget with Weapon Switch Right." },
	{ "FEC_PTT", "Previous target" },
	{ "FEC_PWE", "Previous weapon" },
	{ "FEC_QUE", "???" },
	{ "FEC_R3", "(R3 button)" },
	{ "FEC_RAD", "Radio" },
	{ "FEC_RAL", "RALT" },
	{ "FEC_RCT", "RCTRL" },
	{ "FEC_RED", "Redefine Controls" },
	{ "FEC_RFA", "RIGHT" },
	{ "FEC_RIG", "Right" },
	{ "FEC_RS3", "Radio station cycle (L3 button)" },
	{ "FEC_RSC", "Radio stations" },
	{ "FEC_RSF", "RSHIFT" },
	{ "FEC_RTN", "RET" },
	{ "FEC_RUN", "Run" },
	{ "FEC_RWD", "RWIN" },
	{ "FEC_SFT", "SHIFT" },
	{ "FEC_SLK", "SCROLL LOCK" },
	{ "FEC_SM3", "Sub-mission (R3 button)" },
	{ "FEC_SMS", "Show mouse pointer" },
	{ "FEC_SMT", "Sub-mission" },
	{ "FEC_SPC", "SPC" },
	{ "FEC_SPN", "Sprint" },
	{ "FEC_STR", "NUM STAR" },
	{ "FEC_SUB", "Sub-mission" },
	{ "FEC_SVU", "Save Unsuccessful." },
	{ "FEC_TAB", "TAB" },
	{ "FEC_TAR", "Target" },
	{ "FEC_TDO", "Turn Debug Camera Off" },
	{ "FEC_TFD", "Turret + Lean Down" },
	{ "FEC_TFL", "Look left+Turret L" },
	{ "FEC_TFR", "Look right+Turret R" },
	{ "FEC_TFU", "Turret + Lean Up" },
	{ "FEC_TGD", "Toggle Pad Game/Debug" },
	{ "FEC_TLF", "Next Target To Left" },
	{ "FEC_TRG", "Next Target to Right" },
	{ "FEC_TSS", "Take Screen Shot" },
	{ "FEC_TUC", "Turret control" },
	{ "FEC_TYP", "GAMEPAD TYPE" },
	{ "FEC_UNB", "UNBOUND" },
	{ "FEC_UPA", "UP" },
	{ "FEC_VES", "Vehicle control" },
	{ "FEC_VIB", "Vibration" },
	{ "FEC_WRC", "WINCLICK" },
	{ "FEC_ZIN", "Zoom in" },
	{ "FEC_ZOT", "Zoom out" },
	{ "FEDL_WR", "Deleting saved game. Please wait..." },
	{ "FEDS_TB", "Back" },
	{ "FED_AAS", "ANTI ALIASING" },
	{ "FED_BRI", "Brightness" },
	{ "FED_CLF", "COLOUR FILTER" },
	{ "FED_DBG", "Menu Debug" },
	{ "FED_DFL", "CTheScripts::DbgFlag" },
	{ "FED_DLS", "Big White Debug Light Switched" },
	{ "FED_FLS", "FULLSCREEN" },
	{ "FED_HUD", "HUD MODE" },
	{ "FED_MBL", "MOTION BLUR" },
	{ "FED_MFX", "MATFX" },
	{ "FED_NEO", "NEO" },
	{ "FED_PRM", "PED RIM LIGHT" },
	{ "FED_RDB", "BLIPS ONLY" },
	{ "FED_RDM", "MAP & BLIPS" },
	{ "FED_RDR", "RADAR MODE" },
	{ "FED_RES", "SCREEN RESOLUTION" },
	{ "FED_RGL", "ROAD GLOSS" },
	{ "FED_RID", "Reload IDE" },
	{ "FED_SCP", "gbShowCollisionPolys" },
	{ "FED_SUB", "Subtitles" },
	{ "FED_TRA", "Trails" },
	{ "FED_VPL", "VEHICLE PIPELINE" },
	{ "FED_WIS", "Wide Screen" },
	{ "FED_WLM", "WORLD LIGHTMAPS" },
	{ "FED_WND", "WINDOWED" },
	{ "FEH_AUD", "AUDIO" },
	{ "FEH_BRI", "BRIEF" },
	{ "FEH_DIS", "DISPLAY" },
	{ "FEH_LAN", "LANGUAGE" },
	{ "FEH_MAP", "MAP" },
	{ "FEH_NA", "OPTION NOT AVAILABLE" },
	{ "FEH_SGA", "START NEW GAME" },
	{ "FEH_SSA", "CURSORS TO MOVE - S TO SAVE TO FILE" },
	{ "FEH_STA", "STATS" },
	{ "FELD_WR", "Loading game. Please wait..." },
	{ "FEL_ENG", "English" },
	{ "FEL_FRE", "French" },
	{ "FEL_GER", "German" },
	{ "FEL_ITA", "Italian" },
	{ "FEL_JAP", "JAPANESE" },
	{ "FEL_POL", "POLISH" },
	{ "FEL_RUS", "RUSSIAN" },
	{ "FEL_SPA", "Spanish" },
	{ "FEM_2PR", "PS2 ALPHA TEST" },
	{ "FEM_AUT", "AUTO" },
	{ "FEM_CSB", "CUTSCENE BORDERS" },
	{ "FEM_FRM", "FRAME LIMITER" },
	{ "FEM_HIG", "HIGH" },
	{ "FEM_ISL", "MAP MEMORY USAGE" },
	{ "FEM_LOD", "DRAW DISTANCE" },
	{ "FEM_LOW", "LOW" },
	{ "FEM_MED", "MEDIUM" },
	{ "FEM_MM", "MAIN MENU" },
	{ "FEM_MOB", "MOBILE" },
	{ "FEM_NO", "No" },
	{ "FEM_NON", "NONE" },
	{ "FEM_NRM", "NORMAL" },
	{ "FEM_OFF", "OFF" },
	{ "FEM_OK", "OK" },
	{ "FEM_ON", "ON" },
	{ "FEM_SCF", "SCREEN FORMAT" },
	{ "FEM_SIM", "SIMPLE" },
	{ "FEM_SL1", "Save File 1 Not Present" },
	{ "FEM_SL2", "Save File 2 Not Present" },
	{ "FEM_SL3", "Save File 3 Not Present" },
	{ "FEM_SL4", "Save File 4 Not Present" },
	{ "FEM_SL5", "Save File 5 Not Present" },
	{ "FEM_SL6", "Save File 6 Not Present" },
	{ "FEM_SL7", "Save File 7 Not Present" },
	{ "FEM_SL8", "Save File 8 Not Present" },
	{ "FEM_VSC", "FRAME SYNC" },
	{ "FEM_YES", "Yes" },
	{ "FEO_AUD", "Audio Setup" },
	{ "FEO_CON", "Controller Setup" },
	{ "FEO_DIS", "Display Setup" },
	{ "FEO_LAN", "Language Setup" },
	{ "FEP_OPT", "Options" },
	{ "FEP_QUI", "Quit Game" },
	{ "FEP_RES", "Resume" },
	{ "FEP_STA", "Stats" },
	{ "FEP_STG", "Start Game" },
	{ "FEQ_SRW", "Are you sure you want to quit the game?" },
	{ "FESZ_CA", "Cancel" },
	{ "FESZ_QD", "Proceed with deleting this save game?" },
	{ "FESZ_QO", "Proceed with overwriting this save game?" },
	{ "FESZ_QZ", "Are you sure you want to save this game?" },
	{ "FESZ_WR", "Saving current game. Please wait..." },
	{ "FES_CMI", "LAST MISSION PASSED" },
	{ "FES_CMP", "Save failed! Please try again." },
	{ "FES_DAT", "DATE" },
	{ "FES_DEE", "Delete Failed! Please try again." },
	{ "FES_DEL", "Delete game" },
	{ "FES_DSC", "Delete Successful. Select OK to continue." },
	{ "FES_LCG", "Load the game and continue playing?" },
	{ "FES_LOA", "Load game" },
	{ "FES_NGA", "New Game" },
	{ "FES_SET", "Use Skin" },
	{ "FES_SKN", "SKIN NAME" },
	{ "FES_SSC", "Save Successful. Select OK to continue." },
	{ "FET_AGS", "GAMEPAD SETTINGS" },
	{ "FET_APP", "APPLY" },
	{ "FET_CCR", "IN CAR" },
	{ "FET_CFT", "ON FOOT" },
	{ "FET_CIG", "BACKSPACE TO CLEAR - LMB, RETURN TO CHANGE" },
	{ "FET_CTI", "Classic Controls" },
	{ "FET_CTL", "CONTROLLER SETUP" },
	{ "FET_DAM", "DYNAMIC ACOUSTIC MODELING" },
	{ "FET_DEF", "Restore Defaults" },
	{ "FET_DSN", "Default Player Skin.bmp" },
	{ "FET_EIG", "CANNOT SET A CONTROL FOR THIS ACTION" },
	{ "FET_GFX", "GRAPHICS SETUP" },
	{ "FET_HRD", "DEFAULT SETTINGS RESTORED" },
	{ "FET_LG", "LOAD GAME" },
	{ "FET_MIG", "LEFT, RIGHT, MOUSEWHEEL TO ADJUST" },
	{ "FET_MST", "MOUSE CONTROLLED STEERING" },
	{ "FET_OPT", "OPTIONS" },
	{ "FET_PAU", "PAUSE MENU" },
	{ "FET_PS", "PLAYER SKIN SETUP" },
	{ "FET_QG", "QUIT GAME" },
	{ "FET_RIG", "SELECT A NEW CONTROL FOR THIS ACTION" },
	{ "FET_RSO", "ORIGINAL SETTING RESTORED" },
	{ "FET_SG", "SAVE GAME" },
	{ "FET_STI", "Standard Controls" },
	{ "FET_STS", "STATS SAVED TO 'STATS.HTML' + 'STATS.TXT'" },
	{ "FE_MLG", "MAP LEGEND" },
	{ "HOTRING", "Hotring Racer" },
	{ "ITBEG", "In the beginning..." },
	{ "MAP_LEG", "Map Legend" },
};
